# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PiCamUIDesign.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(498, 496)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 481, 281))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.ImageTab = QtGui.QWidget()
        self.ImageTab.setObjectName(_fromUtf8("ImageTab"))
        self.label_3 = QtGui.QLabel(self.ImageTab)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 81, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.imageSizeComboBox = QtGui.QComboBox(self.ImageTab)
        self.imageSizeComboBox.setGeometry(QtCore.QRect(110, 30, 121, 27))
        self.imageSizeComboBox.setObjectName(_fromUtf8("imageSizeComboBox"))
        self.imagePushButton = QtGui.QPushButton(self.ImageTab)
        self.imagePushButton.setGeometry(QtCore.QRect(320, 200, 121, 27))
        self.imagePushButton.setObjectName(_fromUtf8("imagePushButton"))
        self.imageCheckBox = QtGui.QCheckBox(self.ImageTab)
        self.imageCheckBox.setGeometry(QtCore.QRect(270, 30, 101, 22))
        self.imageCheckBox.setObjectName(_fromUtf8("imageCheckBox"))
        self.label_4 = QtGui.QLabel(self.ImageTab)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 121, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.imagePathLineEdit = QtGui.QLineEdit(self.ImageTab)
        self.imagePathLineEdit.setGeometry(QtCore.QRect(140, 80, 321, 27))
        self.imagePathLineEdit.setMaxLength(1024)
        self.imagePathLineEdit.setObjectName(_fromUtf8("imagePathLineEdit"))
        self.tabWidget.addTab(self.ImageTab, _fromUtf8(""))
        self.VideoTab = QtGui.QWidget()
        self.VideoTab.setObjectName(_fromUtf8("VideoTab"))
        self.label_5 = QtGui.QLabel(self.VideoTab)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 91, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.videoSizeComboBox = QtGui.QComboBox(self.VideoTab)
        self.videoSizeComboBox.setGeometry(QtCore.QRect(110, 30, 121, 27))
        self.videoSizeComboBox.setObjectName(_fromUtf8("videoSizeComboBox"))
        self.videoCheckBox = QtGui.QCheckBox(self.VideoTab)
        self.videoCheckBox.setGeometry(QtCore.QRect(270, 30, 101, 22))
        self.videoCheckBox.setObjectName(_fromUtf8("videoCheckBox"))
        self.label_6 = QtGui.QLabel(self.VideoTab)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 121, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.videoPathLineEdit = QtGui.QLineEdit(self.VideoTab)
        self.videoPathLineEdit.setGeometry(QtCore.QRect(140, 80, 321, 27))
        self.videoPathLineEdit.setObjectName(_fromUtf8("videoPathLineEdit"))
        self.videoPushButton = QtGui.QPushButton(self.VideoTab)
        self.videoPushButton.setGeometry(QtCore.QRect(330, 120, 121, 27))
        self.videoPushButton.setObjectName(_fromUtf8("videoPushButton"))
        self.label_7 = QtGui.QLabel(self.VideoTab)
        self.label_7.setGeometry(QtCore.QRect(10, 190, 181, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_10 = QtGui.QLabel(self.VideoTab)
        self.label_10.setGeometry(QtCore.QRect(10, 120, 191, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.videoLengthSpinBox = QtGui.QSpinBox(self.VideoTab)
        self.videoLengthSpinBox.setGeometry(QtCore.QRect(210, 120, 91, 27))
        self.videoLengthSpinBox.setMinimum(1)
        self.videoLengthSpinBox.setMaximum(10000)
        self.videoLengthSpinBox.setProperty("value", 10)
        self.videoLengthSpinBox.setObjectName(_fromUtf8("videoLengthSpinBox"))
        self.videoSecondsLineEdit = QtGui.QLineEdit(self.VideoTab)
        self.videoSecondsLineEdit.setGeometry(QtCore.QRect(190, 190, 91, 33))
        self.videoSecondsLineEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.videoSecondsLineEdit.setReadOnly(True)
        self.videoSecondsLineEdit.setObjectName(_fromUtf8("videoSecondsLineEdit"))
        self.cancelVideoPushButton = QtGui.QPushButton(self.VideoTab)
        self.cancelVideoPushButton.setGeometry(QtCore.QRect(330, 190, 121, 27))
        self.cancelVideoPushButton.setObjectName(_fromUtf8("cancelVideoPushButton"))
        self.tabWidget.addTab(self.VideoTab, _fromUtf8(""))
        self.TimelapseTab = QtGui.QWidget()
        self.TimelapseTab.setObjectName(_fromUtf8("TimelapseTab"))
        self.label_8 = QtGui.QLabel(self.TimelapseTab)
        self.label_8.setGeometry(QtCore.QRect(20, 30, 81, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.timelapseSizeComboBox = QtGui.QComboBox(self.TimelapseTab)
        self.timelapseSizeComboBox.setGeometry(QtCore.QRect(110, 30, 121, 27))
        self.timelapseSizeComboBox.setObjectName(_fromUtf8("timelapseSizeComboBox"))
        self.timelapseCheckBox = QtGui.QCheckBox(self.TimelapseTab)
        self.timelapseCheckBox.setGeometry(QtCore.QRect(270, 30, 121, 22))
        self.timelapseCheckBox.setObjectName(_fromUtf8("timelapseCheckBox"))
        self.label_9 = QtGui.QLabel(self.TimelapseTab)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 121, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.timelapsePathLineEdit = QtGui.QLineEdit(self.TimelapseTab)
        self.timelapsePathLineEdit.setGeometry(QtCore.QRect(140, 80, 321, 27))
        self.timelapsePathLineEdit.setObjectName(_fromUtf8("timelapsePathLineEdit"))
        self.label_11 = QtGui.QLabel(self.TimelapseTab)
        self.label_11.setGeometry(QtCore.QRect(10, 120, 211, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.timelapseFramesSpinBox = QtGui.QSpinBox(self.TimelapseTab)
        self.timelapseFramesSpinBox.setGeometry(QtCore.QRect(220, 120, 91, 27))
        self.timelapseFramesSpinBox.setMinimum(1)
        self.timelapseFramesSpinBox.setMaximum(100000)
        self.timelapseFramesSpinBox.setProperty("value", 10)
        self.timelapseFramesSpinBox.setObjectName(_fromUtf8("timelapseFramesSpinBox"))
        self.label_12 = QtGui.QLabel(self.TimelapseTab)
        self.label_12.setGeometry(QtCore.QRect(10, 160, 181, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.timelapseDelaySpinBox = QtGui.QSpinBox(self.TimelapseTab)
        self.timelapseDelaySpinBox.setGeometry(QtCore.QRect(220, 160, 91, 27))
        self.timelapseDelaySpinBox.setMaximum(1000)
        self.timelapseDelaySpinBox.setProperty("value", 60)
        self.timelapseDelaySpinBox.setObjectName(_fromUtf8("timelapseDelaySpinBox"))
        self.label_13 = QtGui.QLabel(self.TimelapseTab)
        self.label_13.setGeometry(QtCore.QRect(10, 200, 121, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.timelapsePushButton = QtGui.QPushButton(self.TimelapseTab)
        self.timelapsePushButton.setGeometry(QtCore.QRect(330, 140, 131, 27))
        self.timelapsePushButton.setObjectName(_fromUtf8("timelapsePushButton"))
        self.timelapseFramesLineEdit = QtGui.QLineEdit(self.TimelapseTab)
        self.timelapseFramesLineEdit.setGeometry(QtCore.QRect(140, 200, 101, 33))
        self.timelapseFramesLineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.timelapseFramesLineEdit.setReadOnly(True)
        self.timelapseFramesLineEdit.setObjectName(_fromUtf8("timelapseFramesLineEdit"))
        self.cancelTimelapsePushButton = QtGui.QPushButton(self.TimelapseTab)
        self.cancelTimelapsePushButton.setGeometry(QtCore.QRect(330, 200, 131, 27))
        self.cancelTimelapsePushButton.setObjectName(_fromUtf8("cancelTimelapsePushButton"))
        self.tabWidget.addTab(self.TimelapseTab, _fromUtf8(""))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 350, 141, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.ipAddressLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.ipAddressLineEdit.setGeometry(QtCore.QRect(180, 350, 191, 27))
        self.ipAddressLineEdit.setObjectName(_fromUtf8("ipAddressLineEdit"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 300, 111, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.cameraStatusLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.cameraStatusLineEdit.setGeometry(QtCore.QRect(140, 300, 171, 27))
        self.cameraStatusLineEdit.setReadOnly(True)
        self.cameraStatusLineEdit.setPlaceholderText(_fromUtf8(""))
        self.cameraStatusLineEdit.setObjectName(_fromUtf8("cameraStatusLineEdit"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 390, 151, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.reqPortLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.reqPortLineEdit.setGeometry(QtCore.QRect(180, 390, 71, 27))
        self.reqPortLineEdit.setObjectName(_fromUtf8("reqPortLineEdit"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(20, 430, 131, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.subPortLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.subPortLineEdit.setGeometry(QtCore.QRect(180, 430, 71, 27))
        self.subPortLineEdit.setObjectName(_fromUtf8("subPortLineEdit"))
        self.ConnectPushButton = QtGui.QPushButton(self.centralwidget)
        self.ConnectPushButton.setGeometry(QtCore.QRect(310, 390, 141, 27))
        self.ConnectPushButton.setObjectName(_fromUtf8("ConnectPushButton"))
        self.connectedCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.connectedCheckBox.setEnabled(True)
        self.connectedCheckBox.setGeometry(QtCore.QRect(310, 430, 121, 22))
        self.connectedCheckBox.setCheckable(True)
        self.connectedCheckBox.setObjectName(_fromUtf8("connectedCheckBox"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Pi Cam Controller", None))
        self.label_3.setText(_translate("MainWindow", "Image Size", None))
        self.imagePushButton.setText(_translate("MainWindow", "Capture Image", None))
        self.imageCheckBox.setText(_translate("MainWindow", "Flip Image", None))
        self.label_4.setText(_translate("MainWindow", "Path / File Name", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ImageTab), _translate("MainWindow", "Capture Image", None))
        self.label_5.setText(_translate("MainWindow", "Video Size", None))
        self.videoCheckBox.setText(_translate("MainWindow", "Flip Video", None))
        self.label_6.setText(_translate("MainWindow", " Path / File Name", None))
        self.videoPushButton.setText(_translate("MainWindow", "Capture Video", None))
        self.label_7.setText(_translate("MainWindow", "Video Seconds Captured", None))
        self.label_10.setText(_translate("MainWindow", "Video Length (in Seconds)", None))
        self.cancelVideoPushButton.setText(_translate("MainWindow", "Cancel Video", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.VideoTab), _translate("MainWindow", "Capture Video", None))
        self.label_8.setText(_translate("MainWindow", "Image Size", None))
        self.timelapseCheckBox.setText(_translate("MainWindow", "Flip Images", None))
        self.label_9.setText(_translate("MainWindow", "Path / File Prefix", None))
        self.label_11.setText(_translate("MainWindow", "Number of Frames to Capture", None))
        self.label_12.setText(_translate("MainWindow", "Seconds Between Frames", None))
        self.label_13.setText(_translate("MainWindow", "Frames Captured", None))
        self.timelapsePushButton.setText(_translate("MainWindow", "Start Timelapse", None))
        self.cancelTimelapsePushButton.setText(_translate("MainWindow", "Cancel TImelapse", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TimelapseTab), _translate("MainWindow", "Capture Timelapse", None))
        self.label.setText(_translate("MainWindow", "Camera IP Address", None))
        self.label_2.setText(_translate("MainWindow", "Camera Status", None))
        self.label_14.setText(_translate("MainWindow", "Camera Request Port", None))
        self.label_15.setText(_translate("MainWindow", "Camera Sub Port", None))
        self.ConnectPushButton.setText(_translate("MainWindow", "Connect to Cam", None))
        self.connectedCheckBox.setText(_translate("MainWindow", "Connected", None))

